import React,{useEffect,useRef,useState}from'react';
const ICE={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
export default function VoiceChat({socket,roomId,players=[]}){const pcs=useRef(new Map()),stream=useRef(null),audio=useRef(new Map());const[enabled,setEnabled]=useState(false),[muted,setMuted]=useState(false),[connected,setConnected]=useState(0),[error,setError]=useState('');
const closePeer=id=>{const pc=pcs.current.get(id);if(pc)pc.close();pcs.current.delete(id);const a=audio.current.get(id);if(a)a.remove();audio.current.delete(id);setConnected(pcs.current.size)};
const makePeer=async(target,offer)=>{if(!stream.current)return;let pc=pcs.current.get(target.id);if(!pc){pc=new RTCPeerConnection(ICE);pcs.current.set(target.id,pc);stream.current.getTracks().forEach(t=>pc.addTrack(t,stream.current));pc.onicecandidate=e=>{if(e.candidate)socket.emit('voice-signal',{roomId,targetId:target.id,data:{type:'ice',candidate:e.candidate}})};pc.ontrack=e=>{let a=audio.current.get(target.id);if(!a){a=new Audio();a.autoplay=true;a.playsInline=true;audio.current.set(target.id,a)}a.srcObject=e.streams[0];a.play().catch(()=>{});};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))closePeer(target.id);else setConnected(pcs.current.size)};}if(offer){const o=await pc.createOffer();await pc.setLocalDescription(o);socket.emit('voice-signal',{roomId,targetId:target.id,data:{type:'offer',description:o}})}};
useEffect(()=>{if(!enabled||!roomId)return;const onSignal=async({fromId,data})=>{const target=players.find(p=>p.id===fromId);if(!target)return;try{if(data.type==='offer'){await makePeer(target,false);const pc=pcs.current.get(fromId);await pc.setRemoteDescription(data.description);const a=await pc.createAnswer();await pc.setLocalDescription(a);socket.emit('voice-signal',{roomId,targetId:fromId,data:{type:'answer',description:a}})}else if(data.type==='answer'){const pc=pcs.current.get(fromId);if(pc)await pc.setRemoteDescription(data.description)}else if(data.type==='ice'){const pc=pcs.current.get(fromId);if(pc)await pc.addIceCandidate(data.candidate)}}catch(e){setError('Voice connection failed for one player.')}};socket.on('voice-signal',onSignal);return()=>socket.off('voice-signal',onSignal)},[enabled,roomId,players,socket]);
useEffect(()=>{if(!enabled||!socket.id)return;players.filter(p=>p.id!==socket.id&&socket.id<p.id).forEach(p=>{if(!pcs.current.has(p.id))makePeer(p,true)});return()=>{}},[enabled,players,socket.id]);
useEffect(()=>()=>{pcs.current.forEach(pc=>pc.close());stream.current?.getTracks().forEach(t=>t.stop());audio.current.forEach(a=>a.remove());pcs.current.clear();audio.current.clear()},[]);
const start=async()=>{try{stream.current=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});stream.current.getAudioTracks().forEach(t=>t.enabled=true);setEnabled(true);setError('')}catch(e){setError('Microphone permission was denied or unavailable.')}};
const toggleMute=()=>{const next=!muted;stream.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next)};
return <div className="voice-box"><div><b>🎙 Voice</b><span className="voice-status">{enabled?connected+' peer'+(connected===1?'':'s')+' connected':'Off'}</span></div>{!enabled?<button className="secondary-btn" onClick={start}>Enable Voice</button>:<button className="secondary-btn" onClick={toggleMute}>{muted?'Unmute':'Mute'}</button>}{error&&<small>{error}</small>}</div>}